# Generated by Django 3.2 on 2023-05-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_img', models.ImageField(upload_to='static/img/input')),
                ('output_img', models.ImageField(upload_to='static/img/output')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='关联用户id')),
            ],
        ),
    ]
