# Generated by Django 3.2 on 2023-05-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='input_img',
            field=models.ImageField(upload_to='login/static/img/input'),
        ),
        migrations.AlterField(
            model_name='image',
            name='output_img',
            field=models.ImageField(upload_to='login/static/img/output'),
        ),
    ]
