# Generated by Django 3.2 on 2023-05-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20230504_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='input_img',
            field=models.ImageField(upload_to='img/input'),
        ),
        migrations.AlterField(
            model_name='image',
            name='output_img',
            field=models.ImageField(upload_to='img/output'),
        ),
    ]
