# Generated by Django 3.2 on 2023-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20230505_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='input_img',
            field=models.ImageField(upload_to='input'),
        ),
        migrations.AlterField(
            model_name='image',
            name='output_img',
            field=models.ImageField(upload_to='output'),
        ),
    ]
